config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  get 'homes/about' => 'homes#about'

  devise_for :users

  resources :posts do
    resource :favorite, only: [:create, :destroy]# ネストしてFKのpost_idを取得しやすくする
    resources :comments, only: [:create, :destroy]
  end

  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :comments, dependent: :destroy

    validates :title, presence: true
    validates :body, presence: true

    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
  attachment :profile_image

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        added_attrs = [ :email, :name, :password, :password_confirmation ]
        devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
        devise_parameter_sanitizer.permit :account_update, keys: added_attrs
        devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
    end

    def after_sign_in_path_for(resource)
        user_path(current_user.id)
    end

    def after_sign_out_path_for(resource)
        root_path
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = current_user.comments.build(comment_params)
    comment.post_id = (params[:post_id])
    comment.save
    redirect_back(fallback_location: posts_path)
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_back(fallback_location: posts_path)
  end
  private

  def comment_params
    params.require(:comment).permit(:body)


  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  before_action :set_variables

  def create
    favorite = current_user.favorites.build(post_id: params[:post_id])
    favorite.save
  end

  def destroy
    favorite = Favorite.find_by(user_id: current_user, post_id: params[:post_id])
    favorite.destroy
  end

  private

  def set_variables
    @post = Post.find(params[:post_id])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(@post.user.id)
    @comments = @post.comments
    @comment = Comment.new
    @emoji = TextSentimentAnalysis.new.add_emoji(@post.score, 'Magnitude')
  end

  def new
    @post = Post.new
    @post.body = (params[:content])
  end

  def create
    text_sentiment_analysis = TextSentimentAnalysis.new
    score = text_sentiment_analysis.sentiment_from_text(post_params[:body])
    post = Post.new(post_params)
    post.score = score
    post.user_id = current_user.id
    if post.save
      redirect_to post_path(post.id)
    else
      @post = Post.new(post_params)
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    text_sentiment_analysis = TextSentimentAnalysis.new
    score = text_sentiment_analysis.sentiment_from_text(post_params[:body])
    post = Post.find(params[:id])
    post.score = score
    if post.update(post_params)
      redirect_to post_path(post)
    else
      @post = Post.find(params[:id])
      render 'edit'
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: current_user.id)
    @favorites = Comment.where(user_id: current_user.id)
    @comments = Comment.where(user_id: current_user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user_path(user)
  end
  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>
    <% if post.favorited_by?(current_user) %>
        <td><span></span><%= link_to post.favorites.count, post_favorite_path(post.id), method: :delete, class: 'glyphicon glyphicon-heart aria-hidden="true', remote: true %></td>
    <% else %>
        <p><span></span><%= link_to post.favorites.count, post_favorite_path(post.id), method: :post, class: 'glyphicon glyphicon-heart-empty aria-hidden="true', remote: true %></p>
    <% end %>
<% else %>
    <p><span>お気に入り数: </span><%= post.favorites.count %></p>
<% end %>

app/views/favorites/create.js.erb
$("#favorite-<%= @post.id %>").html("<%= j(render partial: 'favorites/favorite', locals: { post: @post }) %>");

app/views/favorites/destroy.js.erb
$("#favorite-<%= @post.id %>").html("<%= j(render partial: 'favorites/favorite', locals: { post: @post }) %>");

app/views/homes/about.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Gently</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c&display=swap" rel="stylesheet">
  </head>

  <body class="body-wrap">
    <main>

      <section id="sv">
        <div class= "container about-visual"></div>
      </section>

      <div class="container py-5">
        <div class="row justify-content-center py-5">
          <h1 class="service-content">About</h1>
        </div>
        <div class="row align-items-center py-3">
          <div class="col-12 col-md-6 text-center">
            <%= image_tag 'comment.jpg', class: "rounded about-img", size: '350x250' %>
          </div>
          <div class="col-12 col-md-6 mt-3">
            <p class="about-text">
              喋った内容を自動テキスト化し、そのテキストから感情分析が出来るアプリケーションです。<br>
              アプリ内にある『音声聞き取りを開始』ボタンを押すと、<br>
              喋った内容を自動テキスト化することが出来ます。<br>
              また、テキストから感情分析を行いスコアに応じて絵文字を出力します。<br>
              さらに、テキストをアプリケーションに投稿することによって他ユーザーからいいね、コメントを貰うことが出来ます。<br>
            </p>
          </div>
        </div>
      </div>

    </main>
  </body>
</html>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Gently</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c&display=swap" rel="stylesheet">
  </head>

  <body class="body-wrap">
    <main>
      <section id="mv">
        <div class= "container key-visual">
          <h1 class= "display-4 catch">Gently</h1>
          <p class="my-4 head-text">
            自己表現が苦手..そう感じる人々へ<br>
            普段どんな言葉を使っていますか？<br>
            手軽にあなたの感情を分析できるアプリケーションです。
          </p>
          <%= link_to '新規登録はこちら', new_user_registration_path, class: "btn btn-info btn-lg" %>
        </div>
      </section>

      <div class="container py-5">

        <div class="row justify-content-center py-5">
          <h1 class="service-content"></h1>
        </div>

        <div class="row py-2">
          <div class="col-sm-12 col-md-4 text-center py-5">
            <%= image_tag '1boy.jpg', size: '250x250' %>
            <h2 class="my-4">Record</h2>
            <p>話すだけ<br>
              ボタン一つでいつでも簡単に<br>
              始める事ができます。
            </p>
          </div>

          <div class="col-sm-12 col-md-4 text-center py-5">
            <%= image_tag 'egg.jpg', size: '250x250' %>
            <h2 class="my-4">Sentiment</h2>
            <p>感情を見よう<br>
              あなたの言葉を分析します。<br>
              どんな感情になっているでしょうか？
            </p>
          </div>

          <div class="col-sm-12 col-md-4 text-center py-5">
            <%= image_tag 'pc.jpg', size: '250x250' %> <h2 class="my-4">Board</h2>
            <p>共有しよう<br>
              自分の分析結果を<br>
              掲示板で意見交換してみましょう。
            </p>
          </div>
        </div>
        <div class="row justify-content-center pt-3 pb-5"></div>
      </div>
    </main>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Gently</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c&display=swap" rel="stylesheet">
  </head>

  <nav class="navbar navbar-default">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#gnavi">
        <span class="sr-only">メニュー</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
   
    <div id="gnavi" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
        <li><%= link_to '自動音声認識/新規投稿', new_post_path %></li>
        <li><%= link_to 'ユーザー一覧', users_path %></li>
        <li><%= link_to '投稿一覧', posts_path %></li>
        <li><%= link_to 'マイページ', user_path(current_user.id) %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", homes_about_path %></li>
        <li><%= link_to "新規登録", new_user_registration_path %></li>
        <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>

  </nav>

  <body>
    <%= yield %>
  </body>

</html>

app/views/posts/edit.html.erb
<body class="body-wrap">
  <main>

    <section id="ps">
      <div class= "container about-visual">
      </div>
    </section>

    <div class="container py-5">
      <div class="row justify-content-center py-5">
        <h1 class="service-content">編集画面</h1>
      </div>
      <div class="row align-items-center py-3">
        <div class="col-12 col-md-12 text-center">
          <%= form_for(@post) do |f| %>
            <h4>タイトル</h4>
            <%= f.text_field :title %>
            <h4>本文</h4>
            <%= f.text_area :body %>
            <%= f.submit '保存' %>
          <% end %>
          <div class="text-left pt-3"></div>
        </div>
      </div>
    </div>
    
  </main>
</body>

app/views/posts/index.html.erb
<section id="si">
  <div class= "container about-visual"></div>
</section>
  <div class="container py-5">
    <div class="row justify-content-center py-5">
      <h1 class="service-content">投稿一覧</h1>
    </div>
  </div>
<table>
  <thead>
      <tr>
        <th>name</th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="2"></th>
      </tr>
  </thead>
  <% @posts.each do |post|%>
  <tbody>
      <td><%= link_to post.user.name, user_path(post.user.id) %></td>
      <td><%= link_to post.title, post_path(post.id) %></td>
      <td><%= post.body %></td>
      <td id="favorite-<%= post.id %>"><%= render partial: "favorites/favorite", locals: { post: post} %></td>
      <td><span>コメント数: </span><%= post.comments.count %></td>
  </tbody>
  <% end %>
</table>

app/views/posts/new.html.erb
<body class="body-wrap">
  <main>
    <section id="pv">
      <div class= "container about-visual"></div>
    </section>

    <div class="container py-5">
      <div class="row justify-content-center py-5">
        <h1 class="service-content">自動音声認識/新規投稿</h1>
      </div>

      <div class="row align-items-center py-3">
        <div class="col-12 col-md-6 text-center">
          <%= image_tag 'maiku.jpg', class: "rounded about-img", size: '350x250' %>
        </div>

        <div class="col-12 col-md-6 text-center">
          <button id = "btn">音声認識を開始する</button>
          <h4>話した内容</h4>
            <div id = "content"></div>
            
            <%= form_for(@post) do |f| %>
            <div class="col-12 col-md-6 mt-3">
              <h4>タイトル</h4>
                <%= f.text_field :title %>
              <h4>本文</h4>
                <%= f.text_area :body,id: "speech" %>
              <div class="field">
                <%= f.submit '投稿', class:"btn btn-lg btn-maiku" %>
              </div>
            </div>
            <% end %>

        </div>
      </div>
    </div>
  </main>
</body>

app/views/posts/show.html.erb
<body class="body-wrap">
  <main>
    <section id="ps">
      <div class= "container about-visual">
      </div>
    </section>

    <div class="container py-5">
      <div class="row justify-content-center py-5">
        <h1 class="service-content">あなたの感情</h1>
      </div>

      <div class="row align-items-center py-3">
        <div class="col-12 col-md-12 text-center">
          <h1><%= @emoji %></h1>
            <%= @post.body %>

            <% if @user.id == current_user.id %>　
                <%= link_to "edit", edit_post_path(@post.id) %>
                <%= link_to "destroy", post_path(@post), method: :delete, data: {confirm: "本当に削除してよろしいですか？"} %>
            <% end %>

            <h3>コメント一覧</h3>
            <% @comments.each do |comment| %>
            <%= comment.user.name %>
            <%= comment.body %>
                <% if comment.user_id == current_user.id %>
                <%= link_to "Destroy",post_comment_path(comment.post_id,comment.id), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"} %>
                <% end %>
            <% end %>

            <h3>新規コメント</h3>
            <%= form_for [@post, @comment] do |f| %>
                <%= f.text_area :body, rows:'5',placeholder: "コメントをここに", :size => "70*70" %>
                <%= f.submit "送信" %>
            <% end %>
            <div class="text-left pt-3"></div>
      </div>
    </div>
  </main>
</body>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>

    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, class: "name" %>
    </div>

    <div class="field">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "user_image" %>
    </div>

    <div class="field">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "introduction" %>
    </div>

    <div class="actions">
        <%= f.submit %>
    </div>

<% end %>

app/views/users/index.html.erb
<section id="ui">
  <div class= "container about-visual"></div>
</section>

<div class="container py-5">
  <div class="row justify-content-center py-5">
    <h1 class="service-content">ユーザー一覧</h1>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th>name</th>
      <th>show</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <% @users.each do |user| %>
  <tbody>
    <td><%= user.name %></td>
    <td><%= link_to "show", user_path(user.id) %></td>
    <td></td>
  </tbody>
  <% end %>
</table>

app/views/users/show.html.erb
<section id="us">
    <div class= "container about-visual"></div>
</section>

<div class="row justify-content-center">
  <div class="col-12 user-content">
    <div class="row">
      <div class="col-12 col-md-4 mr-2 mb-3">

        <div class="row">
          <div class="col-12 mt-5">
            <%= attachment_image_tag(@user, :profile_image, size: "100x100", class: "rounded-circle", fallback: 'no-image-mini.jpg',:size =>'150x150') %>
          </div>
        </div>

        <div class="row align-items-center">
          <div class="col-12 my-3">
            <div class="row justify-content-center">
              <h4 class="col-3">name： </h4>
              <h3 class="col-6 text-center"><%= @user.name %></h3>
            </div>
            <div class="row justify-content-center">
              <h4 class="col-3">introduce： </h4>
              <h4 class="col-6 text-center"><%= @user.introduction %></h4>
            </div>
            <div class="row justify-content-center">
              <h4 class="col-3">いいね数： </h4>
              <h4 class="col-6 text-center"><%= @favorites.count %></h4>
            </div>
            <div class="row justify-content-center">
              <h4 class="col-3">コメント数： </h4>
              <h4 class="col-6 text-center"><%= @comments.count %></h4>
            </div>
          </div>
        </div>

        <%= link_to "編集する", edit_user_path(@user.id), class: "btn btn-outline-info btn-lg mt-3" %>
      </div>

      <div class="col-12 col-md-7 user-info">
        <div class="row">
          <div class="row align-items-center my-3">
            <div class="col-md-7">
              <h3 class="my-4">投稿一覧</h3>
            </div>
            <div class="col-md-5">
              <%= link_to "新規投稿する", new_post_path, class:"btn btn-info btn-md" %>
            </div>
          </div>
          <% @posts.each do |post| %>
            <div class="col-12 mb-4">
              <div class="row align-items-center  justify-content-center">
                <div class="col-3 col-md-1 mr-md-3">
                </div>
                <div class="col-6 col-md-3">
                  <h5 class="text-center"><%= post.title %></h5>
                </div>
                <div class="col-6 col-md-3">
                  <h5 class="text-center"><%= post.body %></h5>
                </div>
                <div class="col-md-6 mt-2 mt-md-0">
                  <%= link_to "編集", edit_post_path(post.id), class: "btn btn-outline-info mr-3"%>
                  <%= link_to "削除", post_path(post.id), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn btn-outline-danger"%>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>